USER_EMAIL_MAX_LENGTH = 255
USER_PASSWORD_MAX_LENGTH = 255

CATEGORY_NAME_MAX_LENGTH = 100

NOTE_TITLE_MAX_LENGTH = 200
NOTE_CONTENT_MAX_LENGTH = 10_000


ANTIBRUTE_MAX_ATTEMPTS = 5
ANTIBRUTE_WINDOW_SEC = 60
ANTIBRUTE_BLOCK_SEC = 300
ANTIBRUTE_FAIL_DELAY = 0.4
